---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-checker
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: # place a role name here witch can push metrics to CloudWatch (use svc-eks-checker.json policy for that role)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: eks-checker
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: eks-checker
        spec:
          serviceAccountName: eks-checker
          containers:
          - command:
            - /bin/sh
            - -c
            - python /opt/eks_checker.py
            name: eks-checker
            image: # put the image path which was built from the Dockerfile
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
