---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-checker
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: # set the role ARN (use svc-ebs-checker.json policy for that role) to be able to push metrics
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ebs-checker
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ebs-checker
        spec:
          serviceAccountName: ebs-checker
          containers:
          - command:
            - /bin/sh
            - -c
            - python /opt/ebs_checker.py
            name: ebs-checker
            image: # set your image here
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
